"""empty message

Revision ID: 2593b64b7e7e
Revises: 
Create Date: 2020-10-15 00:09:46.587864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2593b64b7e7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('saab', sa.String(length=1), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=False),
    sa.Column('cell_no', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('religion', sa.String(), nullable=False),
    sa.Column('education', sa.String(), nullable=False),
    sa.Column('blood_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
